[workspace]
members = [
    "packages/stylist",
    "packages/stylist-core",
    "packages/stylist-macros",

    "examples/benchmarks",
    "examples/yew-integration",
    "examples/yew-shadow",
    "examples/yew-theme-context",
]
resolver = "2"
